### ISSUE TITLE
"Rem" line is not highlighted as a comment

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#108]
Although, this does not cause any issue with the compilation, it quickly gets confusing and annoying when dealing with old code.

Here is an example:

![image](https://user-images.githubusercontent.com/47574584/172988152-1077adea-fb66-41b1-b94d-d771b6f3305f.png)

**Comment by RhoSigma-QB64** [comment]
This is actually known. It was considered and discussed at least 2 times (that's what I remember) in the old QB64.org forum. Somehow the final conlusion was always to leave it that way. People voted for comment highlighting when using the apostroph, but for regular highlighting with `REM` in favor of having `REM` highlighted as keyword. I personally would combine it, highlighting `REM` as keyword and the remaining line as comment. But that was AFAIK the problem, so that Fellippe said you can have the one (whole line incl. 'REM` as comment) or the other (`REM` as keyword and theremaining line as usual).

However, it's certainly worth a closer look, if the combined highligting is really off the road with the current highlighter implementation. So I'd label it as "enhancement" for now, not as a "bug".

**Comment by RhoSigma-QB64** [comment]
And I knew there was something else: https://discord.com/channels/975381912350752819/975485884944236554/984670319535079434

**Comment by a740g** [comment]
Wow. It's weird that people wanted REMs to be colored this way. I use `' TODO:` for placeholders. These things are a personal preference, I guess. Still, I'd would love to see a toggle for this in the IDE sometime in the future. Thank you @RhoSigma-QB64

**Comment by mkilgore** [comment]
I'd be fine with keeping this open for the toggle option, but I'll be honest that it'll be near the bottom of the list compared to the other stuff we'd like to get to :-/ Though perhaps someone else would be interested in picking it up :)

**Comment by dkearns** [comment]
An old PR for this without toggle for keyword REM and comment to EOL - https://github.com/QB64Team/qb64/pull/139

**Comment by RhoSigma-QB64** [comment]
@dkearns , your suggested changes were incorporated into the **Phoenix rebranding** pull request #136 .
