### ISSUE TITLE
"Size" elements in the _MEM type should be _Unsigned Long or _Unsigned _Integer64 (depending on the arch)

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#123]
Currently the `_MEM` type is defined as follows. This makes it difficult to use `SIZE` and `ELEMENTSIZE` in code.

```VB
TYPE memory_type
    OFFSET AS _OFFSET       'start location of block(changes with byte position)
    SIZE AS _OFFSET         'size of block remaining at offset(changes with position)
    TYPE AS LONG            'type description of variable used(never changes)
    ELEMENTSIZE AS _OFFSET  'byte size of values inside the block(never changes)
    IMAGE AS LONG           'the image handle used when _MEMIMAGE(handle) is used
END TYPE
```

For example, the following code gives an error:

```VB
Dim p As _Mem
```
`...`
```VB
Dim s As _Integer64
s = p.SIZE ' SIZE is an _OFFSET and QB64 does not like this!
```

For 32-bit versions of QB64 `_MEM` should be defined as:
```VB
TYPE memory_type
    OFFSET AS _OFFSET
    SIZE AS _UNSIGNED LONG
    TYPE AS LONG
    ELEMENTSIZE AS _UNSIGNED LONG
    IMAGE AS LONG
END TYPE
```

For 64-bit versions of QB64 `_MEM` should be defined as:
```VB
TYPE memory_type
    OFFSET AS _OFFSET
    SIZE AS _UNSIGNED _INTEGER64
    TYPE AS LONG
    ELEMENTSIZE AS _UNSIGNED _INTEGER64
    IMAGE AS LONG
END TYPE
```

**Comment by RhoSigma-QB64** [comment]
Since QB64 v2.0, hence also in ALL QB64-PE versions, `_CV` and `_MK$` can be used to convert `_OFFSET` values.

        a& = 0
        DIM m AS _MEM
        m = _MEM(a&)
        b& = _CV(LONG, _MK$(LONG, m.SIZE))
        PRINT b&

As far as I know it was discussed several times to change the entries, but for some good reasons it was not done. Instead the alterative with `_CV` and `_MK$` was implemented. I'll need to dig up the discussions in the old forum.

**Comment by a740g** [comment]
Something similar was suggested by offbyone on a [Discord thread](https://discord.com/channels/592061709485735966/973039653076746322/990453493259182120). Then he suggested that I should submit an issue.

However, something about this 2-step conversion feels wrong. Probably it's just me. 🙂

**Comment by RhoSigma-QB64** [comment]
It also turned out, that our Wiki page regarding `_MEM` was not up to date. I've merged our Wiki page with the latest info available (actually the help\\_MEM.txt file from the last development build of QB64.org) and updated it. Especially notice the red important note, obviously it was even considered better to change the `m.TYPE` entry from `LONG` to `_OFFSET` too, rather than making `m.SIZE` and `m.ELEMENTSIZE` into `LONG` or `_INTEGER64`.

I'm really not familiar with the `_MEM `internals, so my best guess is they made it architecture independent using `_OFFSET`, and leave it to the special case situation in each program to deal with it as required by using the `_OS$` function or the pre-compiler to find out 32/64 bit and then convert the values to whatever needed.

This was however complicated before v2.0 using a method invented by Steve: [ConvertOffset](https://github.com/SteveMcNeill/Steve64/blob/master/Archives/BAS%20Files/Convert%20Offset.bas)

And that's probably the reason for the compromise allowing to use `_CV` and `_MK$` to convert offsets.

**Comment by RhoSigma-QB64** [comment]
For reasons mentioned by Steve [here](https://discord.com/channels/975381912350752819/975485884944236554/990614196620242978), it becomes obvious why the `_OFFSET` type was chosen for the entries.

As it makes absolutely sence to use a "flexible" data type here, rather than implementing a proper structure packing/padding for each possible OS, we probably won't go to mess with it in the near future.

**Comment by mkilgore** [comment]
We can talk about it later but personally I don't agree with this decision. @a740g identified a real problem with trying to use `_MEM`, I don't think this should need a workaround. As far as different structures per platform, there are only two sizes to support so I don't think that's really a good justification. Otherwise we should consider introducing a new integer type for sizes that doesn't have `_Offset` limitations, then you wouldn't need to do conversations and could just use the integer type normally. Other languages like C have a type like `size_t` for this purpose, which is a normal integer but a different size per platform.

**Comment by RhoSigma-QB64** [comment]
Well, `_OFFSET` is in principle the same on the C/C++ side. It's `ptsizint` or `uptszint` here, which its size is defined somewhere (common.h??) according to the used architecture. So rather than introducing yet another integer type, we should simply remove the restrictions on `_OFFSET`. As far as I can tell, it's just the performed IDE/Syntax/Compiler checks, which prevent us from using it like any other integer type on the BASIC side of things.
