### ISSUE TITLE
"bad CPU type in executable" reported by Apple M1 user

### ISSUE THREAD

**Issue by loopy750** [QB64-Phoenix-Edition/QB64pe#155]
A user has reported my program doesn't work on their Apple M1. Some searching revealed that it could be incompatibility with the hardware. Is this likely? And also I read if they install something called Rosetta 2, this should in theory allow incompatible macOS-compiled programs to run on these systems.

**Comment by mkilgore** [comment]
Apple M1 is ARM based, but QB64-PE currently only supports x86-based CPUs, so what you're seeing is expected. We have had people try to use it on ARM on Linux with varying levels of success, but it's not something we offer out-of-the-box. Additionally because of this, any program compiled on Mac OS using QB64-PE will be an x86 program, and thus not natively runnable on Apple M1.

If you delve into the internals of QB64-PE a bit you may be able to trick it to cross-compile for ARM Mac OS from an x86 Mac OS, I imagine this is possible but I don't think any of us working on QB64-PE know how to do that. Additionally even if you do this it's likely things aren't entirely compatible and thus you'll encounter bugs or it just won't compile without changes.

I'm not super familiar with Rosetta since I don't use a Mac, but I do understand that its purpose is to allow running x86 executables on Apple M1, so presumably it should work for any QB64-PE compiled program (though there might be a performance penalty).

**Comment by loopy750** [comment]
That pretty much confirms what I was thinking too. Thanks for the detailed explanation. I guess all I'll do is recommend they look into Rosetta and if that works, it works, as I'm not a Mac user either.
