### ISSUE TITLE
Feature request: Option to turn off "Alt toggle" for activating menu

### ISSUE THREAD

**Issue by vivid-pixel** [QB64-Phoenix-Edition/QB64pe#207]
If the user is switching back and forth between program windows with Alt-Tab, when they come back to QB64PE they have to press Alt to resume editing their code and not inadvertently activate a menu in the IDE. One example of when this becomes an inconvenience is if a user is working on a single screen and switching between a tutorial and the QB64PE IDE. When returning to the IDE it's easy to forget Alt was toggled on and it ends up adding a lot of extra key presses.

My idea is an extra setting for **Alt button toggles menu**. When disabled, the Alt button must be _held_ (common on GUI applications) to activate any menu options, so when the user comes back to the IDE window they may resume typing code immediately.

**Comment by mkilgore** [comment]
I didn't realize it worked that way to be honest, I agree that behavior could be annoying. There seems to already be logic around whether Alt is held vs. released so it hopefully wouldn't be _too_ hard to add as an optional setting.

**Comment by vivid-pixel** [comment]
I just tried QB64PE on Windows for the first time, and looks like the Alt key works works better: Alt-Tabbing out of the program and back will not toggle on the menu, only if you press Alt by itself.
So I guess this is a glitch on Linux and OS X.

**Comment by mkilgore** [comment]
Good catch, you're right. I've tried it in both Linux and Windows now and see the same behavior you're seeing (it works in Windows, doesn't in Linux).

It seems this behavior is actually intentional, see qb64team/qb64#1. Literally, the code has a `IF _WINDOWHASFOCUS OR os$ = "LNX" THEN` to skip the behavior you want. Personally I don't really get it, I agree with you that the behavior is annoying in reference to `Alt+Tab`, I imagine it was a bit of an [xkcd 1172](https://xkcd.com/1172/) situation when it was first changed 😆 

Regardless, I'm certainly open to changing it and I'm not sure if an IDE flag is necessary to enable the current behavior. I think the only question is whether it introduces some other weird behavior in Linux that was the original cause for the change (Ex. Maybe `_WINDOWHASFOCUS` is bugged or something). It should be easy enough to test though, I don't have time to try at the moment but we should be able to just revert that commit and see what the behavior is.

**Comment by vivid-pixel** [comment]
Workaround to get the desired behavior on Linux:
On my Mac laptop it's Command+Tab, so Windows+Tab on a typical keyboard. That swaps back and forth between windows _exactly_ like I'd expect Alt+Tab to do, as the shortcuts seem to have the same behavior using GNOME. The only difference is it avoids this decision to handle Alt in a special way. That kind of thing is why comments are important in code!

**Comment by flukiluke** [comment]
#499 fixes this issue for Linux and it should be far more minor on mac OS which uses cmd-tab for window switching.
