### ISSUE TITLE
Sound playback from embedded data

### ISSUE THREAD

**Issue by KingMocker** [QB64-Phoenix-Edition/QB64pe#232]
Create a `_SNDOPENBUFFER` type of command that just takes a string that already contains the file contents for the sound you want to play. 
So, you could store a regular mp3 (or similar) in your exe and play it directly.

Issue created as requested by DSMan195276 after a post in a thread the Help Me forum.

**Comment by a740g** [comment]
Just to be clear... So, is this like opening a sound file from memory rather than reading it out of storage? Honestly, I like this, and I would like something like this for image files too. I've seen plenty of code where people embed stuff in the executable and then write it to storage and then load it using `_SNDOPEN` or `_LOADIMAGE`. Although it works, it is slow (due to performance penalty of hitting slow storage) and sometimes may not be possible in environments where there is no writeable storage, or the storage has run out of space.

My idea would be to simply extend _SNDOPEN and _LOADIMAGE to load stuff directly from memory.

For sounds (soundHandle& = _SNDOPEN(fileName$[, capabilities$])) we could do:
```VB
handle& = _SNDOPEN(mybuffer$, "memory") ' here "memory" would mean a memory buffer instead of a file name
```

For images (handle& = _LOADIMAGE(filename$[, mode%])) we could do:
```VB
handle& = _LOADIMAGE(mybuffer$, 32 OR 1024) ' here 1024 would set a bit for a memory buffer instead of a file name
```

Also linking https://github.com/QB64-Phoenix-Edition/QB64pe/issues/28 to this.

**Comment by RhoSigma-QB64** [comment]
Best idea ever :)

**Comment by a740g** [comment]
> Best idea ever :) But mayby calling it `_LOADIMAGEMEM` and `_SNDOPENMEM` respectively instead of overloading the existing command names.

But this would mean we would add two new keywords and must write up two new wiki pages. I already wrote eight and my fingers hurt.😝 And then there will be some people who'll call us out and say we are adding bloat. 😉

Just kidding. I am good with this too.

**Comment by SpriggsySpriggs** [comment]
Very cool idea. Would make embedding images and sound files so much easier. No more BIN2BAS files. Ooooh. I'd also be able to put that into effect for my FLAC player and my API stuff that grabs images from the web. Very exciting stuff, guys.

**Comment by SpriggsySpriggs** [comment]
Maybe you can add a switch to those keywords. Something like `_FromString`. So `_LoadImage _FromString string$`
