### ISSUE TITLE
_SndRaw does not work in stereo mode

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#27]
_SndRaw does not play stereo streams correctly. It sounds like a mono stream no matter which channel is being fed. As far as I can tell, this is not an issue with my system.

Dim h As Long, i As Long
h = _SndOpenRaw
For i = 1 To 100000
    _SndRaw Sin(i / 10), 0, h
Next
For i = 1 To 100000
    _SndRaw 0, Sin(i / 10), h
Next
_SndClose h

Can someone run the above snippet and let me know if this works as expected for them?

I am using QB64pe v0.5.0

**Comment by a740g** [comment]
Oh, and _SndRawLen always returns 0 no matter how many seconds of data are left to be played by SndRaw.

Let me know if you want me to submit a new issue for this.

**Comment by mkilgore** [comment]
Just wanted to let you know I was able to confirm this behavior, and it seems like a bug to me. Rather than just play the left/right audio there's clearly some mixing going on. The code for all of this is in `./internal/c/parts/audio/out/src.c`, and even when I manually modified it to set the right sample to zero it played nothing during the second loop but I still heard right-side audio during the first loop.

I would also recommend submitting a separate bug for `_SndRawLen`, I don't think it's really related to this. I haven't look too closely but my very initial guess is just that it's because `func__sndrawlen()` calculates the length left by checking how many buffers left. I don't think that counts buffers that are queued to play, so presumably `_SndRawLen` could return zero while audio is still playing because all the audio is already queued up in OpenAL. SDL had a `SDL_GetQueuedAudioSize()` that could be used to roughly solve this problem, OpenAL may have something similar we could use. That might not be a full solution though because that includes queued audio _other_ than the SndRaw as well, so we might need to do some math and tracking or something...

**Comment by a740g** [comment]
Thank you. I'll dig up those files and see if I can find anything.

For _sndrawlen, the wiki says:
The _SNDRAWLEN function returns the length, in seconds, of a sound currently queued.
Use _SNDRAWLEN to determine the length of a sound queue during creation and when to stop playing the sound.
Ensure that _SNDRAWLEN is comfortably above 0 (until you've actually finished playing sound).
If you are getting occasional random clicks, this generally means that _SNDRAWLEN has dropped to 0.

So, this does not behave like the wiki says. I'll submit a separate bug like you asked.

Thanks again.

**Comment by a740g** [comment]
@mkilgore @SteveMcNeill @RhoSigma-QB64
This can be closed now that we have [v3.1.0](https://github.com/QB64-Phoenix-Edition/QB64pe/releases/tag/v3.1.0) out?

**Comment by RhoSigma-QB64** [comment]
Fixed in #156, #157.
