### ISSUE TITLE
ctime()

### ISSUE THREAD

**Issue by Sanmayce** [QB64-Phoenix-Edition/QB64pe#291]
Hi,
this issue was reported on QB64PE 32-bit v3.5.0:
https://qb64phoenix.com/forum/showthread.php?tid=1182&pid=12742#pid12742

**Comment by mkilgore** [comment]
Hi :) This isn't a bug with QB64-PE, your C++ code isn't compatible with the newer version of MinGW that comes with QB64-PE. The `time_t` situation on Windows is a bit annoying, you probably want to look at using some of the `_stat64*` functions on Windows which are more exact in what types they use for the times and file sizes (32-bit vs. 64-bit integers), along with maybe `_ctime64` which always takes the 64-bit `time_t` (`__time64_t`).

**Comment by Sanmayce** [comment]
Thank you for clarifying, usually I avoid these messy old/new cross-platform non-standard stuff, was forced to.
Anyway, found that the compiler complaints are good start (in fact finish) to resolve the issue, just enforced the demanded cast.

As a side thing, could you consider, in the future, adding a compile options in IDE e.g. "-O3 -mavx" which are to be passed to the recompile.sh/recompile.bat, in a form of a single string?! This will ease the development and increase compile-time friendliness for users not wanting to deal outwith IDE.

Wish you luck with enhancing QB64, for us.

**Comment by mkilgore** [comment]
Welcome, and yeah Windows is a pain, I ran into this same issue last week or so as well. It's dumb because your code is correct, MinGW's `stat64` in this case is not standard because the members are not `time_t`.

> As a side thing, could you consider, in the future, adding a compile options in IDE e.g. "-O3 -mavx" which are to be passed to the recompile.sh/recompile.bat, in a form of a single string?! This will ease the development and increase compile-time friendliness for users not wanting to deal outwith IDE.

We actually already have that :) An IDE dialog for this was added in v0.8.0, and a `-f` compiler flag was added in v3.2.0, they allow you to supply extra compiler and linker options when building your code. Check the `Options` menu in the IDE or pass `-f` to the compiler to see all the available settings.
