### ISSUE TITLE
File created using BIN2INCLUDE is extremely large in v3.7.0 vs v3.6.0

### ISSUE THREAD

**Issue by loopy750** [QB64-Phoenix-Edition/QB64pe#350]
Attached is the (slightly modified) output from BIN2INCLUDE converting a file called `cross.png` to `cross.png.BM`.

Compiled with QB64 3.6.0, the file output is 5,655 bytes, as expected.
Compiled with QB64 3.7.0 or 3.8.0, the file output is 10,000,000 bytes.

Is there something in the code that needs changing, or is it to do with the compiler?
[cross.png.zip](https://github.com/QB64-Phoenix-Edition/QB64pe/files/11779741/cross.png.zip)

**Comment by mkilgore** [comment]
This one came up on the forum a while back, the actual issue here is that your compressed version of the png is not correct, it doesn't decompress successfully with any version. In v3.7.0 we swapped zlib for miniz and that changed the behavior of failed decompressions such that the size of the buffer ends up as 10,000,000 (where-as previously the result tended to be, but was not always, the size of the amount of successfully decompressed data).

Unfortunately we don't report the decompression error to you, that was a mistake made back when `_INFLATE$()` was implemented, and that's also why it appeared to work correctly in v3.6.0 and below despite the decompression actually failing. We did talk a bit about modifying miniz to make it work more similar to zlib, but fundamentally the compressed data just needs to be fixed, then the problem goes away.

My personal guess is that there's a bug in `BIN2INCLUDE` somewhere when converting the `_DEFLATE$()` result into string data and back, it cuts off the end or something which makes the decompression fail. You could confirm this by doing a `_DEFLATE$()` in v3.6.0 and comparing the result to whatever is in `btemp$` when it gets passed to `_INFLATE$()`, the strings won't match.

**Comment by loopy750** [comment]
Thanks for that, and yes I just realised _INFLATE$() was causing it. Unfortunately the dev deactivated his GitHub some time ago, but the internet usually doesn't forget. I'll look further into it and update with any findings.

**Comment by loopy750** [comment]
I think I've worked it out, but there's a bit of an issue. A fork is available here:
https://github.com/tailscreatesstuff32/BIN2INCLUDE

The `BIN2BAS` SUB of `BIN2INCLUDE.BAS` I'm able to modify,

FIND: `If Len(INDATA$) - BC& < 3 Then`
directly after, add:
```
                a$ = Mid$(INDATA$, BC&, 3)
                BC& = BC& + 3: LL& = LL& + 4
                Print #2, E$(a$) + Q$;
                Exit Do
```
Basically it's doing what the beginning of the loop does one more time, as the last characters are otherwise missing (hence causing the error). The `Exit Do` is there to prevent it continuing to `Case 0, Case 1` etc, as it doesn't seem to be required, and isn't a match if run.

Looking at `pic2mem.bas`, I'm assuming the four lines to be added will do the same thing, however, it's asking for these two files
```
'$INCLUDE:'StripDirectory$.BM'
'$INCLUDE:'Replace.BM'
```

I just happen to have `pic2mem.exe` on my PC, but I can't compile `pic2mem.bas` because of those missing files.

**Comment by a740g** [comment]
@loopy750 I fixed BIN2INCLUDE with the fix @mkilgore suggested here: https://qb64phoenix.com/forum/showthread.php?tid=1662&pid=15728#pid15728

I migrated the tool to use the new InForm-PE and integrated pic2mem. So, everything related to the tool is inside `BIN2INCLUDE.bas`. 

Download the updated sources from here: https://github.com/a740g/QB64-Museum/tree/main/SpriggsySpriggs/Bin2Include

Feel free to close the issue if there are no more concerns.

**Comment by a740g** [comment]
Yeah. I changed the code to generate the `INFLATE$` size (for both `bin2bas` and `pic2mem`). So, with newly generated code, it should not create 10,000,000 bytes files.

Also, specifying the `INFLATE$` size makes the code run faster because then `INFLATE$` does not have to guess the correct buffer size. https://qb64phoenix.com/qb64wiki/index.php/INFLATE$

However, the encoding algorithm has an issue as you rightly pointed out in the post above. If you patch both bin2bas and pic2mem routines, please share a copy with me or open a PR.

**Comment by loopy750** [comment]
It's very straight forward, within https://github.com/a740g/QB64-Museum/blob/main/SpriggsySpriggs/Bin2Include/source/BIN2INCLUDE.bas

after lines 134 & 249 (`IF LEN(INDATA$) - BC& < 3 THEN`), I inserted

```
                ' loopy750: added code
                a$ = Mid$(INDATA$, BC&, 3)
                BC& = BC& + 3: LL& = LL& + 4
                Print #2, E$(a$) + Q$;
                Exit Do ' exit now because the code below isn't required
                '
```

It's still a little "messy", as the `Select Case` code just below it is now not needed nor run, but I've kept it in just in case it's one day explained why it was added. I'm a little curious to understand why it was done like that when it causes a deflate/inflate mismatch.
