### ISSUE TITLE
Menu bar Crash

### ISSUE THREAD

**Issue by AtomicSlaughter** [QB64-Phoenix-Edition/QB64pe#52]
when using the menu bar, the program hangs, and behaves like it is stuck in a do..loop.

windows 11
AMDe3020 with vega graphics
4gb ram

**Comment by SpriggsySpriggs** [comment]
Is the program maximized?

**Comment by struttas** [comment]
does all the time

**Comment by SteveMcNeill** [comment]
Fresh install in a new directory?  You didn't install over an old version, by chance?

**Comment by struttas** [comment]
this is a fresh install, first time ive ran qb64pe

**Comment by mkilgore** [comment]
I take it that it just happens randomly? Does it take a while to occur, or does it happens instantly?

It might help if you get a memory dump of the process when it is stuck and give it to us, you can get one via Task Manager by finding the process and then Right Click -> Create dump file. Admittedly I have yet to try using a dump from QB64 though, I suspect it will be of limited use because we strip the symbols and don't store them anywhere.

If it does turn out to be useless than the next best step would be to modify the build of QB64 to stop stripping the executable at compile time and store the symbols near the end of the build so we can use them later for debugging. Then you could recreate the issue on the new QB64, take a new memory dump, and we could use the symbols to see where exactly it's stuck.

**Comment by mkilgore** [comment]
If you were trying to do a search when it froze then #57 might be related, I found a fix for that one.

**Comment by SteveMcNeill** [comment]
Fixed with endless search loop correction, according to OP.  Closing for now, unless someone else reports issues once again like this.
